name: ICMP Ping Monitor

on:
  workflow_dispatch:  # Enables manual trigger
  schedule:
    - cron: "*/1 * * * *"  # Runs every minute

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Check Target Status
        id: check
        run: |
          target="https://google.com"
          if curl -s --head $target | grep "200 OK"; then
            echo "status=up" >> $GITHUB_ENV
          else
            echo "status=down" >> $GITHUB_ENV
            exit 1
          fi


      - name: Log Downtime or Uptime
        if: always()
        run: |
          if [ "$status" == "down" ]; then
            echo "$(date): Target is DOWN" >> downtime.log
          else
            echo "$(date): Target is UP" >> uptime.log
          fi

      - name: Upload Logs
        uses: actions/upload-artifact@v3
        with:
          name: ping-logs
          path: |
            downtime.log
            uptime.log
