name: ICMP Ping Monitor

on:
  workflow_dispatch:  # Enables manual trigger
  schedule:
    - cron: "*/1 * * * *"  # Runs every minute

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
    - name: Check Target Status
      id: ping
      run: |
        target="${{ secrets.MYSTATICIP01 }}"
        if ping -c 1 $target; then
          echo "status=up" >> $GITHUB_ENV
        else
          echo "status=down" >> $GITHUB_ENV
          exit 1
        fi

      - name: Log Downtime or Uptime
        if: always()
        run: |
          if [ "${{ steps.ping.outputs.status }}" == "down" ]; then
            echo "$(date): Target is DOWN" >> downtime.log
          else
            echo "$(date): Target is UP" >> uptime.log
          fi

      - name: Upload Logs
        uses: actions/upload-artifact@v3
        with:
          name: ping-logs
          path: |
            downtime.log
            uptime.log
